### PR TITLE
Fix search suggestions

### PR DESCRIPTION
**Pull request by rhoerr**
### Description (*)

Fixes autocomplete search suggestions pulling terms from non-searchable fields.

Cherry-pick of changes from `2.4-develop` to `release/1.x`.

### Related Pull Requests
#102 
#104 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by fballiano — APPROVED** [review]

**Comment by fballiano** [comment]
@rhoerr it seems to me the PR is complete, about the checkpoints, is there a README to write?

**Comment by rhoerr** [comment]
> @rhoerr it seems to me the PR is complete, about the checkpoints, is there a README to write?

I don't think that applies for this one. This is the relevant module readme: https://github.com/mage-os/mageos-magento2/blob/e31c588dd262be976341fd80dfd675f901e3c605/app/code/Magento/Elasticsearch/README.md

That checkbox probably almost never applies, actually, except in cases where a core module is being added or completely overhauled. For us, any changes of that nature would be in separate modules and repositories to avoid BC issues.

**Comment by fballiano** [comment]
the I think this is ready to merge

**Comment by fballiano** [comment]
@rhoerr I'd squash this specific one, seems more appropriated to me

**Pull request merged**
