### PR TITLE
Update Branding

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
Updates the admin footer and logo to Mage-OS branding.

### Manual Testing Scenarios (*)
1. Navigate to the admin login page
2. Observe that the Magento logo is replaced with the Mage-OS logo
---
1. Log into the admin
3. Observe that the logo has been updated to be the Mage-OS logo
4. Observe that the footer references Mage-OS
5. Observe that the copyright notice logo links to the Mage-OS website
6. Observe that the privacy policy and bug report links navigate to their Mage-OS counterparts

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rhoerr** [comment]
> 1. The copyright notice icon in the footer remains to be updated - I will likely need additional input/guidance on how we want to change that, if at all.

The M logo is Adobe's intellectual property, we won't be able to reuse it at all even if it's in the normal Magento repository (I'm pretty sure). So we'll need to replace or remove that icon in the footer, yes. I lean toward removing it personally -- I'm not sure what that little icon adds.

We'll also need to replace any M favicons in the repository.

> 2. Do we want to change the name of the logo file from magento-icon.svg to mageos-icon.svg and update the relevant code to use this new name instead?

For the same reason as above -- yes, I think we need to update the logo filename as well.

Things I see remaining (here or in separate PRs as appropriate):
- [ ] Change or remove the footer M logo
- [ ] Replace any M favicons
- [ ] Change the admin logo filename
- [ ] Change the 'Report an issue' footer URL (and the privacy policy URL?)
- [ ] Change the footer message (in place of copyright) -- maybe to 'Learn more about [Mage-OS](https://mage-os.org)', or 'Thanks for using Mage-OS', or 'Provided by the Mage-OS Association', or similar.

Thank you!

**Comment by pykettk** [comment]
Thanks, @rhoerr ! 

> The M logo is Adobe's intellectual property, we won't be able to reuse it at all even if it's in the normal Magento repository (I'm pretty sure). So we'll need to replace or remove that icon in the footer, yes. I lean toward removing it personally -- I'm not sure what that little icon adds.

I'll do that as part of this PR 👍 

> We'll also need to replace any M favicons in the repository.

I'll replace any of the other admin area icons and open a separate PR for the remaining ones.

> I think we need to update the logo filename as well.

Not a problem, I'll make the necessary changes soon - I should have some time in the next couple of days or so 🙂 

> Change the 'Report an issue' footer URL (and the privacy policy URL?)

Happy to do that too!

> Change the footer message (in place of copyright) -- maybe to 'Learn more about [Mage-OS](https://mage-os.org/)', or 'Thanks for using Mage-OS', or 'Provided by the Mage-OS Association', or similar.

I like this idea too. I think a thanks and a link to the website would be nice 🙂 Something like `Thank you for choosing Mage-OS. [Learn more about Mage-OS](https://mage-os.org/).` perhaps?

**Comment by rhoerr** [comment]
> I like this idea too. I think a thanks and a link to the website would be nice 🙂 Something like "Thank you for choosing Mage-OS. [Learn more about Mage-OS](https://mage-os.org/)." perhaps?

That sounds great! Thanks.

**Comment by pykettk** [comment]
1. Admin footer logo removed
2. Admin logo filenames changed (including login page)
3. Privacy policy and bug report links updated to Mage-OS equivalents
4. Footer messaged changes

### Admin Login Page
admin-login-page

### Admin Dashboard
The bottom half of the page looks slightly weird thanks to Chrome's full page screenshot tool.

admin-dashboard

**Comment by pykettk** [comment]
There are a few remaining instances of files pointing to the old Magento logo however these are all static URLs and I could not find a similar URL for the Mage-OS logo as it is an inline SVG on `mage-os.org`.

old-logo-refs

**Comment by rhoerr** [comment]
Pardon the delay. I installed this on an instance, and it looks great! We're getting closer to a release, which means getting this merged in. 🙂

I found some more branded images:
- https://github.com/mage-os/mageos-magento2/blob/2.4-develop/lib/web/images/logo.svg
- https://github.com/mage-os/mageos-magento2/blob/2.4-develop/pub/errors/default/images/logo.gif
- https://github.com/mage-os/mageos-magento2/blob/2.4-develop/app/design/frontend/Magento/blank/web/images/logo.svg
- https://github.com/mage-os/mageos-magento2/blob/2.4-develop/app/code/Magento/Email/view/frontend/web/logo_email.png
- https://github.com/mage-os/mageos-magento2/blob/2.4-develop/app/code/Magento/Theme/view/frontend/web/favicon.ico
- https://github.com/mage-os/mageos-magento2/blob/2.4-develop/app/code/Magento/Theme/view/adminhtml/web/favicon.ico
- https://github.com/mage-os/mageos-magento2/blob/2.4-develop/app/code/Magento/Theme/view/install/web/favicon.ico
- https://github.com/mage-os/mageos-magento2/blob/2.4-develop/setup/pub/images/favicon/favicon.ico
- https://github.com/mage-os/mageos-magento2/blob/2.4-develop/pub/errors/default/images/favicon.ico

The favicon is most visible. Favicon can maybe be based on https://mage-os.org/wp-content/uploads/2023/03/cropped-logo-mark-180x180.png

Thank you!

**Comment by pykettk** [comment]
Thanks, @rhoerr 🙂 I'll make some time to look at this soon - likely next weekend or the week following that 🤞

**Comment by rhoerr** [comment]
Hi @pykettk, were you able to look at this? If you can't make time, that's okay. We're looking at merging within a matter of days.

**Comment by pykettk** [comment]
@rhoerr Not yet - I had to push this down my list 🙁 I'll make time to look at this tomorrow for sure though - likely to be from around 4PM/5PH BST🙂

**Comment by rhoerr** [comment]
Awesome, thank you @pykettk! All looks good to me.

**Review by rhoerr — APPROVED** [review]

**Review by rhoerr — APPROVED** [review]

**Review by Vinai — APPROVED** [review]

**Pull request merged**
