### PR TITLE
Phpcs test

### PR DESCRIPTION
**Pull request by MeetKamal**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sprankhub** [comment]
@MeetKamal, thanks for your work here!

I just looked at the changes and I am a bit confused :) I pretty much expected one added file under `.github/workflows/`. Instead, there are 1549 changed files and many of those changes seem to be unrelated. Actually, https://github.com/MeetKamal/mageos-magento2/blob/phpcs_test/coding-standard/action.yml looks like the only file needed for it? Could you check and clean it up? It might be easier to start with a new clean branch and then just adding the necessary change to it.

**Comment by MeetKamal** [comment]
Hi @sprankhub 

As discussed created new branch and deployed required changes, Please review below branch 

https://github.com/MeetKamal/mageos-magento2/tree/phpcs_baseline

**Comment by sprankhub** [comment]
@MeetKamal, could you create a new PR with the new branch and verify that only necessary files are changed?

**Comment by sprankhub** [comment]
Closing this in favour of #24.

**Pull request closed without merging**
