### PR TITLE
Disable Admin Usage Data Collection by Default

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
Updates default behaviour to disable the data collection implemented by `Magento_AdminAnalytics`.

### Fixed Issues
Fixes mage-os/mageos-magento2#43

### Manual testing scenarios (*)
1. Install the 1.0.0 preview and log into the backend as an admin user.
2. Observe the related configuration option is disabled upon installation
    - `Stores -> Settings -> Configuration -> Advanced -> Admin -> Admin Usage`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by Vinai — CHANGES_REQUESTED** [review]
Thank you for your PR!
There are a number of additional places that need to be changed, too.

The module is still referenced in the mageos-magento2 root composer.json:
 https://github.com/mage-os/mageos-magento2/blob/2.4-develop/composer.json#L114

Also the module PageBuilderAdminAnalytics is built on top of it, and the composer package
`mage-os/module-page-builder-admin-analytics` depends on `mage-os/module-admin-analytics`.
https://github.com/mage-os/mageos-magento2-page-builder/tree/develop/app/code/Magento/PageBuilderAdminAnalytics

This module in turn is required in the page-builder metapackage:
https://github.com/mage-os/mageos-magento2-page-builder/blob/develop/app/code/Magento/_metapackage/composer.json#L8

Given it is likely more modules also depend on the AdminAnalytics module, and we want to promote Mage-OS as a drop-in replacement for Magento Open Source, I think it probably is better to short-circuit it instead of removing it.

Maybe we automatically opt-out of data collection as a first step. If we can go further and disable tracking on a deeper level without removing the module that would be good, too.

Removal then should be scheduled for a later date.

**Comment by pykettk** [comment]
Thanks, @Vinai ! I've changed the contents of this PR to now disable the collection by default instead of removing the module itself 👍

**Comment by Vinai** [comment]
@pykettk Does this hide the modal on the initial login into the admin panel?

**Comment by pykettk** [comment]
@Vinai Just to echo my message elsewhere, it looks like I lost a commit when rebasing 🤦‍♂️ I'll re-commit my change in a few moments. I had opted to rely on the value of the related admin config option to determine whether to show this block or not, rather than simply never showing it.

**Comment by Vinai** [comment]
Thank you! Very good.

I wonder, do we change the URL in here?
```
            <block name="tracking" as="tracking" template="Magento_AdminAnalytics::tracking.phtml" ifconfig="admin/usage/enabled">
                <arguments>
                    <argument name="tracking_url" xsi:type="string">//assets.adobedtm.com/a7d65461e54e/37baabec1b6e/launch-177bc126c8e6.min.js</argument>
                    <argument name="metadata" xsi:type="object">Magento\AdminAnalytics\ViewModel\Metadata</argument>
                </arguments>
            </block>
```
I guess we should set up our own tracking as an alternative 🤣

**Comment by pykettk** [comment]
Change it for real or to something ineffective? Sorry, tone is hard through text 😅

**Comment by Vinai** [comment]
Probably we should use some black hole URL.

**Comment by pykettk** [comment]
> Probably we should use some black hole URL.

Any one you're particularly interested in using?

**Comment by Vinai** [comment]
Or we could submit even more troll values, like version 2.4.7-p2 enterprise edition.

**Comment by Vinai** [comment]
No idea what to use. I would have to search for one.

**Comment by pykettk** [comment]
Removing the value renders a `<script>` tag with an empty `src` value - perhaps this is sufficient? We could also edit the template to only produce output if the `tracking_url` argument exists? 🤷‍♂️

**Comment by Vinai** [comment]
Let's just remove the script value so it renders an empty script src.

**Review by Vinai — APPROVED** [review]

**Pull request merged**
