### PR TITLE
Mage-OS admin rebrand

### PR DESCRIPTION
**Pull request by rhoerr**
### Description (*)

Basic rebranding of the admin theme, without any structural changes. Shifts the color scheme to blues, gets rid of dark table headers, adds border radius to fields, and other small adjustments.

### Related Pull Requests
Builds on https://github.com/mage-os/mageos-magento2/pull/21 for Mage-OS logo and brand changes

### Manual testing scenarios (*)
1. Deploy static content
2. Access admin panel
3. Confirm admin panel looks good

### Questions or comments
I am not a designer, and this is an early and relatively small effort, so there is room for improvement. But I think this is an accessible and meaningful improvement over the existing theme, and provides a direction for improvement over time.

There's been discussion of greater improvements (like changing the menu to purely CSS for performance and stability), but in the interest of time I've stuck to minor style changes only at this point. Others are more than welcome to propose further and deeper changes, provided the changes won't cause issues for compatibility.

Screenshots of the work to date:
Screenshot 2023-09-22 214749
Screenshot 2023-09-22 214937
Screenshot 2023-09-22 214952
Screenshot 2023-09-22 215112
Screenshot 2023-09-22 215253

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rhoerr** [comment]
Note, I chose green for the main button color rather than Mage-OS orange because the contrast of white on green is far better than white on orange (5.5 vs 2.3). More readable and accessible.

**Comment by rhoerr** [comment]
I fixed the coding standard warnings, and made some other small adjustments (better odd-row color, fixed gray hover background throughout; red flush-cache button).

The one lingering standards warning is a false positive; it is correctly indented.
```
FILE: ...to2/app/design/adminhtml/Magento/backend/web/css/styles-old.less
----------------------------------------------------------------------
FOUND 0 ERRORS AND 4 WARNINGS AFFECTING 4 LINES
----------------------------------------------------------------------
 783 | WARNING | Line indented incorrectly; expected 4 spaces, found 8
 784 | WARNING | Line indented incorrectly; expected 4 spaces, found 8
 785 | WARNING | Line indented incorrectly; expected 4 spaces, found 8
 786 | WARNING | Line indented incorrectly; expected 4 spaces, found 8
----------------------------------------------------------------------
```

**Comment by rhoerr** [comment]
I'll adjust the fly-out menu title gray color for better contrast.

**Comment by rhoerr** [comment]
I've adjusted that header text color. Color contrast is now 7.68.

image

**Review by Vinai — APPROVED** [review]

**Pull request merged**
