### PR TITLE
Added Sansec eComscan Security Scan Workflow

### PR DESCRIPTION
**Pull request by fballiano**
This PR addresses https://github.com/mage-os/infrastructure/issues/46 adding a workflow for Sansec eComscan.

Notes:
- there's no documentation of the action and it's [not listed in the marketplace](https://github.com/marketplace?query=ecomscan), is it legit?
- would we want to enable sansec online report ([demo here](https://dashboard.sansec.io/d/ecomscan/report/demo))? Does MageOS have a publicly viewable sansec user?
- I couldn't test the action because the license key is only visible within MageOS organization thus my fork can't run the workflow.

### CODE REVIEW

**Comment by fballiano** [comment]
@rhoerr it seems the action can't see the license key, can we debug it somehow?

**Comment by sprankhub** [comment]
I reviewed this and think it should work. @danslo, any idea? The secret is set on the org-level, which works for other secrets:

image

**Comment by fballiano** [comment]
@sprankhub I've tried a few things but couldn't get it to work so I've opened an issu upstream, let's see.

**Comment by fballiano** [comment]
I've rewritten the workflow (also because I wanted to use a different set of options) and created the same secret on my fork, and [it works fine](https://github.com/fballiano/mageos-magento2/actions/runs/12416122710/job/34664451805), this should mean that there's a problem with the secret in the organization, I've never seen such a problem because I use org-secrets a lot..

@rhoerr could you recreate the secret and see if there are some visibility options?

**Comment by rhoerr** [comment]
I don't have direct access to the org settings, so it's a bit of a process to get in. I can do that tonight if nobody beats me to it. Per Simon's screenshot earlier, I set the key to public repo visibility, which I expect would mean it's accessible here. This is my first use of org keys though.

**Comment by fballiano** [comment]
A failing (with hardcoded malware in a test file) [works too](https://github.com/fballiano/mageos-magento2/actions/runs/12416585002/job/34665556797) on my fork (I've added some output).

**Comment by fballiano** [comment]
@rhoerr I use many of those, for example for this workflow https://github.com/MahoCommerce/maho/blob/main/.github/workflows/sync-l10n-repo.yml and I never had any problems. Maybe it's possible that's not visible to a PR because it comes from a fork... it could be possible, but if it is that way it means we've to merge to test

**Comment by fballiano** [comment]
it makes sense, then we have to merge and manually run the action via workflow_dispatch

**Comment by rhoerr** [comment]
If that limitation would apply to other PRs too, it maybe defeats the purpose of the scan somewhat. It sounds like there's a workaround by changing `pull_request` to `pull_request_target`, with the caveat of risks involved: https://stackoverflow.com/questions/76952023/how-to-make-github-actions-safely-access-secrets-for-prs-created-from-forks

**Comment by fballiano** [comment]
Since the action only checks-out the code but never executes (nor does a composer install) it I think we're fine.

I've switched to pull_request_target, let's see what happens

**Comment by fballiano** [comment]
note:

Screenshot 2024-12-19 alle 16 42 36

also, if we want this workflow on all branches, we should add the workflow file to all of them

**Review by rhoerr — APPROVED** [review]

**Comment by fballiano** [comment]
I'm testing that this works in https://github.com/mage-os/mageos-magento2/pull/113

**Comment by fballiano** [comment]
tests are positive, @sprankhub @rhoerr do you want to directly cherry-pick b30bda9 on the other branches?

**Comment by gwillem** [comment]
Great job guys!

**Pull request merged**
