### PR TITLE
Update Product Name Metadata to Mage-OS

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
Update the product name metadata from `Magento` to `Mage-OS`.

### Manual testing scenarios (*)
1. Navigate to the `magento_version` route
2. Observe the version is `Mage-OS/*`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Vinai** [comment]
Note:
Tests don't seem to refer to the changed name as a constant.
* `\Magento\Version\Controller\Index\IndexTest::testIndexAction` checks if the value of `getName` is present in the response body
* `\Magento\Webapi\JsonGenerationFromDataObjectTest` uses the value of `getName` as part of the expected JSON
* `\Magento\Framework\App\Test\Unit\ProductMetadataTest::testGetName` only checks if the value is not empty
* `\Magento\Dhl\Test\Unit\Model\CarrierTest::testBuildSoftwareName` uses a mock to provide the value

**Comment by Vinai** [comment]
The Magento2 coding standard violations are present also in the upstream version of the file.  
Should we fix them in one of the following ways?
A) by adding the appropriate comments to disable them  
B) by addressing the complaints? Will adding a visibility of `public` to the constants break any descendants overriding the constant? A quick search didn't reveal and new implementation for the methods annotated with `@deprecation`. Do we add a stub comment to satisfy the coding standard?

**Comment by sprankhub** [comment]
So Magento currently does not run phpcs on `lib` code at least!? :thinking:

**Comment by pykettk** [comment]
I think I'd lean towards option A at the moment, given the infancy of the project and the seeming desire to want to stay as close to 1:1 as possible in the near term. That being said, I have no _real_ preference, personally - I'm happy to go with whatever the general consensus is 🙂

**Comment by Vinai** [comment]
I remember seeing somewhere that in upstream `phpcs` is run with `--severity=7`, but I don't remember where.
I've now spent an hour looking without success. I might be mistaken...
That would explain however why the core files don't trigger the warnings we are getting here.

**Comment by Vinai** [comment]
@sprankhub pointed out this [marketplace guide](https://developer.adobe.com/commerce/marketplace/guides/sellers/code-sniffer/#tools-and-environments-used) where extensions are checked with error-severity 10 only.

**Comment by Vinai** [comment]
Once https://github.com/graycoreio/github-actions-magento2/pull/130 is merged, the severity can be configured to 10 and we can move this PR forward.

**Review by Vinai — APPROVED** [review]

**Pull request merged**
